on:
  push:
    branches:
      - main
name: docs

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: panvimdoc
        uses: kdheepak/panvimdoc@main
        with:
          vimdoc: neorg-extras
          version: "Neovim >= 0.8.0"
          demojify: true
          treesitter: true

      - name: Stash changes
        id: stash
        run: |
          git diff --exit-code || git stash --include-untracked

      - name: Pull latest changes from remote
        run: git pull --rebase origin main

      - name: Apply stashed changes if they exist
        if: steps.stash.outputs.stashed == 'true'
        run: git stash pop || true

      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "auto-generate vimdoc"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
          commit_author: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
